In [ ]:
!pip install autogluon pandas scikit-learn

Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.16.3)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.6.1)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.42.68-py3-none-any.whl.metadata (6.7 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting ray<2.53,>=2.43.0 (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0->autogluon)
  Downloading ray-2.52.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (18.1.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (0.2.7)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (11.3.0)
Collecting torch<2.10,>=2.6 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 2.7 MB/s eta 0:00:00
Collecting transformers<4.58,>=4.51.0 (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.13.0)
Requirement already satisfied: fsspec<=2025.3 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (2025.3.0)
Collecting jsonschema<4.24,>=4.18 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.2 MB/s eta 0:00:00
Collecting torchvision<0.25.0,>=0.21.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.3.0)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.19.0)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.4.2-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (4.6.0)
Collecting huggingface_hub<1.0 (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting xgboost<3.2,>=2.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading xgboost-3.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.0 kB)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (2.8.7)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (0.8.2)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.8.11)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (1.5.3)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading fugue-0.9.7-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (3.11.7)
Collecting chronos-forecasting<2.4,>=2.2.2 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading chronos_forecasting-2.2.2-py3-none-any.whl.metadata (23 kB)
Collecting peft<0.18,>=0.13.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (5.9.5)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (26.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (0.7.0)
Collecting botocore<1.43.0,>=1.42.68 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading botocore-1.42.68-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (5.24.1)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (4.0.0)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.70.16)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.7)
Requirement already satisfied: fastcore>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.12.24)
Requirement already satisfied: fasttransform>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.1.5)
Requirement already satisfied: plum-dispatch in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (2.7.1)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (3.1.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (3.13.3)
Collecting triad>=1.0.1 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading triad-1.0.2-py3-none-any.whl.metadata (6.6 kB)
Collecting adagio>=0.2.6 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading adagio-0.2.6-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (2.12.3)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (3.25.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (1.3.2)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (1.0.0)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (0.10.9.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.5.0->autogluon) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.30.0)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting pytorch-lightning (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.3.2)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.60.0)
Collecting optuna (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Collecting window-ops (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading window_ops-0.0.15-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.5.0->autogluon) (5.2.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (2025.11.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf<2.4.0,>=2.1.1->autogluon.multimodal==1.5.0->autogluon) (4.9.3)
Collecting colorama (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting model-index (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading model_index-0.1.11-py3-none-any.whl.metadata (3.9 kB)

In [ ]:
import pandas as pd
import numpy as np

from autogluon.tabular import TabularPredictor
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/df_all_clean (1).csv')

print(df.shape)
df.head()

(7333, 25)

,discode,Sex,agey,agem,aged,nation,occupat,addercode,metropol,treatmentloc,...,datefound,datedeath,germ,complications,district,province,death,days_to_death,days_to_define,days_to_report
0,66.0,หญิง,17,5,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,2018-01-01,NaN,NaN,NaN,ปากพลี,นครนายก,0.0,NaN,0.0,0.0
1,66.0,ชาย,52,8,1,ไทย,รับจ้าง-กรรมกร,14081305,ในเขตเทศบาล,ร.พ.ชุมชน,...,2018-01-01,NaN,NaN,NaN,ผักไห่,พระนครศรีอยุธยา,0.0,NaN,0.0,0.0
2,66.0,ชาย,55,0,0,ไทย,รับจ้าง-กรรมกร,14110303,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,2018-01-01,NaN,9.0,0.0,วังน้อย,พระนครศรีอยุธยา,0.0,NaN,0.0,0.0
3,66.0,ชาย,39,0,0,ไทย,รับจ้าง-กรรมกร,14100605,อบต,ร.พ.ชุมชน,...,2018-01-01,NaN,0.0,0.0,ลาดบัวหลวง,พระนครศรีอยุธยา,0.0,NaN,0.0,0.0
4,66.0,ชาย,51,3,24,ไทย,รับจ้าง-กรรมกร,14051102,ในเขตเทศบาล,ร.พ.ชุมชน,...,2018-01-01,NaN,NaN,NaN,บางบาล,พระนครศรีอยุธยา,0.0,NaN,0.0,0.0

In [ ]:
df.columns

Index(['discode', 'Sex', 'agey', 'agem', 'aged', 'nation', 'occupat',
       'addercode', 'metropol', 'treatmentloc', 'patienttype', 'results',
       'treatmentloccod', 'datesick', 'datedefine', 'datefound', 'datedeath',
       'germ', 'complications', 'district', 'province', 'death',
       'days_to_death', 'days_to_define', 'days_to_report'],
      dtype='object')

In [ ]:
# change to datetime

df["datesick"] = pd.to_datetime(df["datesick"], errors="coerce")
df["datefound"] = pd.to_datetime(df["datefound"], errors="coerce")

In [ ]:
# วันในสัปดาห์ที่ report [ 0 : Monday , 6 :	Sunday ]

df["report_weekday"] = df["datefound"].dt.weekday

In [ ]:
# เดือนที่มีการ report

df["report_month"] = df["datefound"].dt.month

In [ ]:
# จำนวนเคสในวันเดียวกัน

df["cases_same_day"] = (
    df.groupby("datesick")["datesick"]
    .transform("count")
)

In [ ]:
# จำนวนเคสในอำเภอในวันเดียวกัน

df["district_cases_day"] = (
    df.groupby(["district","datesick"])["datesick"]
    .transform("count")
)

In [ ]:
# จำนวนเคสทั้งหมดที่รักษาในสถานพยาบาลนั้น

df["hospital_load"] = (
    df.groupby("treatmentloc")["treatmentloc"]
    .transform("count")
)

In [ ]:
# วันในสัปดาห์ที่ผู้ป่วยเริ่มป่วย

df["sick_weekday"] = df["datesick"].dt.weekday

In [ ]:
# เริ่มป่วย weekend มั้ย [1 : weekend , 0 : weekday]

df["is_weekend_sick"] = df["sick_weekday"].isin([5,6]).astype(int)

In [ ]:
# จำนวนเคสทั้งหมดในจังหวัด

province_cases = df.groupby("province").size()

df["province_case_count"] = df["province"].map(province_cases)

In [ ]:
# จำนวนเคสทั้งหมดในอำเภอ

district_cases = df.groupby("district").size()

df["district_case_count"] = df["district"].map(district_cases)

In [ ]:
# เลือก Feature

features = [
"agey",
"Sex",
"province",
"district",
"occupat",
"discode",
"treatmentloc",
"cases_same_day",
"district_cases_day",
"hospital_load",
"province_case_count",
"district_case_count",
"report_weekday",
"report_month",
"is_weekend_sick",
"days_to_report"
]

In [ ]:
# เตรียม Dataset

df_model = df[features]

In [ ]:
# ลบ Missing Target

df_model = df_model.dropna(subset=["days_to_report"])

In [ ]:
# Split Dataset

train_data, test_data = train_test_split(
    df_model,
    test_size=0.2,
    random_state=42
)

In [ ]:
# train model

predictor = TabularPredictor(
    label="days_to_report",
    problem_type="regression",
    eval_metric="mae"
).fit(
    train_data,
    presets="high_quality"
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260315_045809"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Mon Feb  2 12:27:57 UTC 2026
CPU Count:          2
Pytorch Version:    2.9.1+cu128
CUDA Version:       CUDA is not available
Memory Avail:       10.91 GB / 12.67 GB (86.1%)
Disk Space Avail:   74.75 GB / 107.72 GB (69.4%)
===================================================
Presets specified: ['high_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2026-03-15 04:58:34,724	INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
		Context path: "/content/AutogluonModels/ag-20260315_045809/ds_sub_fit/sub_fit_ho"
(_dystack pid=3067) Running DyStack sub-fit ...
(_dystack pid=3067) Beginning AutoGluon training ... Time limit = 880s
(_dystack pid=3067) AutoGluon will save models to "/content/AutogluonModels/ag-20260315_045809/ds_sub_fit/sub_fit_ho"
(_dystack pid=3067) Train Data Rows:    5213
(_dystack pid=3067) Train Data Columns: 15
(_dystack pid=3067) Label Column:       days_to_report
(_dystack pid=3067) Problem Type:       regression
(_dystack pid=3067) Preprocessing data ...
(_dystack pid=3067) Using Feature Generators to preprocess the data ...
(_dystack pid=3067) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=3067) 	Available Memory:                    10041.56 MB
(_dystack pid=3067) 	Train Data (Original)  Memory Usage: 2.35 MB (0.0% of available memory)
(_dystack pid=3067) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=3067) 	Stage 1 Generators:
(_dystack pid=3067) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=3067) 			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=3067) 	Stage 2 Generators:
(_dystack pid=3067) 		Fitting FillNaFeatureGenerator...
(_dystack pid=3067) 	Stage 3 Generators:
(_dystack pid=3067) 		Fitting IdentityFeatureGenerator...
(_dystack pid=3067) 		Fitting CategoryFeatureGenerator...
(_dystack pid=3067) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=3067) 	Stage 4 Generators:
(_dystack pid=3067) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=3067) 	Stage 5 Generators:
(_dystack pid=3067) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=3067) 	Useless Original Features (Count: 1): ['discode']
(_dystack pid=3067) 		These features carry no predictive signal and should be manually investigated.
(_dystack pid=3067) 		This is typically a feature which has the same value for all rows.
(_dystack pid=3067) 		These features do not need to be present at inference time.
(_dystack pid=3067) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=3067) 		('float', [])  : 6 | ['cases_same_day', 'district_cases_day', 'province_case_count', 'district_case_count', 'report_weekday', ...]
(_dystack pid=3067) 		('int', [])    : 3 | ['agey', 'hospital_load', 'is_weekend_sick']
(_dystack pid=3067) 		('object', []) : 5 | ['Sex', 'province', 'district', 'occupat', 'treatmentloc']
(_dystack pid=3067) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=3067) 		('category', [])  : 5 | ['Sex', 'province', 'district', 'occupat', 'treatmentloc']
(_dystack pid=3067) 		('float', [])     : 6 | ['cases_same_day', 'district_cases_day', 'province_case_count', 'district_case_count', 'report_weekday', ...]
(_dystack pid=3067) 		('int', [])       : 2 | ['agey', 'hospital_load']
(_dystack pid=3067) 		('int', ['bool']) : 1 | ['is_weekend_sick']
(_dystack pid=3067) 	0.1s = Fit runtime
(_dystack pid=3067) 	14 features in original data used to generate 14 features in processed data.
(_dystack pid=3067) 	Train Data (Processed) Memory Usage: 0.35 MB (0.0% of available memory)
(_dystack pid=3067) Data preprocessing and feature engineering runtime = 0.14s ...
(_dystack pid=3067) AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
(_dystack pid=3067) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=3067) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=3067) Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=3067) User-specified model hyperparameters to be fit:
(_dystack pid=3067) {
(_dystack pid=3067) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=3067) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=3067) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=3067) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=3067) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=3067) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=3067) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=3067) }
(_dystack pid=3067) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=3067) Fitting 106 L1 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 586.75s of the 880.33s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.20%)
(_dystack pid=3067) 	-2.4227	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	35.96s	 = Training   runtime
(_dystack pid=3067) 	0.42s	 = Validation runtime
(_dystack pid=3067) Fitting model: LightGBM_BAG_L1 ... Training model for up to 541.36s of the 834.94s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.21%)
(_dystack pid=3067) 	-2.2609	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	30.21s	 = Training   runtime
(_dystack pid=3067) 	0.13s	 = Validation runtime
(_dystack pid=3067) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 506.30s of the 799.89s of remaining time.
(_dystack pid=3067) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.0/9.3 GB
(_dystack pid=3067) 	-2.0255	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	6.27s	 = Training   runtime
(_dystack pid=3067) 	0.33s	 = Validation runtime
(_dystack pid=3067) Fitting model: CatBoost_BAG_L1 ... Training model for up to 499.61s of the 793.19s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.03%)
(_dystack pid=3067) 	-2.1837	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	182.79s	 = Training   runtime
(_dystack pid=3067) 	0.14s	 = Validation runtime
(_dystack pid=3067) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 312.76s of the 606.34s of remaining time.
(_dystack pid=3067) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
(_dystack pid=3067) 	-1.9175	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	2.27s	 = Training   runtime
(_dystack pid=3067) 	0.27s	 = Validation runtime
(_dystack pid=3067) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 310.14s of the 603.72s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.04%)
(_dystack pid=3067) 	-2.1724	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	106.33s	 = Training   runtime
(_dystack pid=3067) 	0.47s	 = Validation runtime
(_dystack pid=3067) Fitting model: XGBoost_BAG_L1 ... Training model for up to 199.43s of the 493.01s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.13%)
(_dystack pid=3067) 	-2.0077	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	33.25s	 = Training   runtime
(_dystack pid=3067) 	0.31s	 = Validation runtime
(_dystack pid=3067) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 157.99s of the 451.57s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.02%)
(_ray_fit pid=6770) 	Ran out of time, stopping training early. (Stopping on epoch 31)
(_ray_fit pid=7031) 	Ran out of time, stopping training early. (Stopping on epoch 41)
(_ray_fit pid=7039) 	Ran out of time, stopping training early. (Stopping on epoch 42)
(_ray_fit pid=7304) 	Ran out of time, stopping training early. (Stopping on epoch 39)
(_ray_fit pid=7583) 	Ran out of time, stopping training early. (Stopping on epoch 40)
(_dystack pid=3067) 	-2.1138	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	169.37s	 = Training   runtime
(_dystack pid=3067) 	0.89s	 = Validation runtime
(_dystack pid=3067) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 277.60s of remaining time.
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
(_dystack pid=3067) 	Ensemble Weights: {'ExtraTreesMSE_BAG_L1': 0.421, 'NeuralNetTorch_BAG_L1': 0.263, 'RandomForestMSE_BAG_L1': 0.158, 'XGBoost_BAG_L1': 0.105, 'NeuralNetFastAI_BAG_L1': 0.053}
(_dystack pid=3067) 	-1.8552	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	0.33s	 = Training   runtime
(_dystack pid=3067) 	0.0s	 = Validation runtime
(_dystack pid=3067) Fitting 106 L2 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 277.24s of the 277.14s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.25%)

(_ray_fit pid=8276) [1000]	valid_set's l1: 2.23779

(_dystack pid=3067) 	-2.0432	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	36.58s	 = Training   runtime
(_dystack pid=3067) 	0.44s	 = Validation runtime
(_dystack pid=3067) Fitting model: LightGBM_BAG_L2 ... Training model for up to 231.74s of the 231.64s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.23%)
(_ray_fit pid=7585) 	Ran out of time, stopping training early. (Stopping on epoch 40)
(_dystack pid=3067) 	-2.1463	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	36.52s	 = Training   runtime
(_dystack pid=3067) 	0.25s	 = Validation runtime
(_dystack pid=3067) Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 190.23s of the 190.13s of remaining time.
(_dystack pid=3067) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.0/9.2 GB
(_dystack pid=3067) 	-1.9033	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	15.53s	 = Training   runtime
(_dystack pid=3067) 	0.3s	 = Validation runtime
(_dystack pid=3067) Fitting model: CatBoost_BAG_L2 ... Training model for up to 174.31s of the 174.21s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.11%)
(_dystack pid=3067) 	-1.6947	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	83.65s	 = Training   runtime
(_dystack pid=3067) 	0.1s	 = Validation runtime
(_dystack pid=3067) Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 86.43s of the 86.32s of remaining time.
(_dystack pid=3067) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
(_dystack pid=3067) 	-1.8511	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	5.26s	 = Training   runtime
(_dystack pid=3067) 	0.29s	 = Validation runtime
(_dystack pid=3067) Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 80.77s of the 80.67s of remaining time.
(_dystack pid=3067) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.06%)
(_ray_fit pid=9686) No improvement since epoch 7: early stopping
(_ray_fit pid=9873) No improvement since epoch 1: early stopping [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_ray_fit pid=10130) No improvement since epoch 7: early stopping [repeated 2x across cluster]
(_ray_fit pid=10294) No improvement since epoch 8: early stopping
(_ray_fit pid=10347) No improvement since epoch 7: early stopping
(_dystack pid=3067) 	-2.2393	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	103.41s	 = Training   runtime
(_dystack pid=3067) 	0.66s	 = Validation runtime
(_dystack pid=3067) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the -26.97s of remaining time.
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
(_dystack pid=3067) 	Ensemble Weights: {'CatBoost_BAG_L2': 0.933, 'ExtraTreesMSE_BAG_L2': 0.067}
(_dystack pid=3067) 	-1.6926	 = Validation score   (-mean_absolute_error)
(_dystack pid=3067) 	0.35s	 = Training   runtime
(_dystack pid=3067) 	0.0s	 = Validation runtime
(_dystack pid=3067) AutoGluon training complete, total runtime = 907.82s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 253.4 rows/s (652 batch size)
(_dystack pid=3067) Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
(_dystack pid=3067) Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
(_dystack pid=3067) 	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
(_dystack pid=3067) 	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
(_dystack pid=3067) 	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
(_dystack pid=3067) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: LightGBMXT_BAG_L1_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
(_dystack pid=3067) 	2.6s	 = Training   runtime
(_dystack pid=3067) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: LightGBM_BAG_L1_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.6 GB
(_dystack pid=3067) 	0.35s	 = Training   runtime
(_dystack pid=3067) Fitting model: RandomForestMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=3067) 	6.27s	 = Training   runtime
(_dystack pid=3067) 	0.33s	 = Validation runtime
(_dystack pid=3067) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: CatBoost_BAG_L1_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0
(_dystack pid=3067) 	16.88s	 = Training   runtime
(_dystack pid=3067) Fitting model: ExtraTreesMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=3067) 	2.27s	 = Training   runtime
(_dystack pid=3067) 	0.27s	 = Validation runtime
(_dystack pid=3067) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/9.4 GB
(_dystack pid=3067) No improvement since epoch 2: early stopping
(_dystack pid=3067) 	7.5s	 = Training   runtime
(_dystack pid=3067) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: XGBoost_BAG_L1_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0
(_dystack pid=3067) 	0.23s	 = Training   runtime
(_dystack pid=3067) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: NeuralNetTorch_BAG_L1_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/9.4 GB
(_dystack pid=3067) 	16.76s	 = Training   runtime
(_dystack pid=3067) Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=3067) 	Ensemble Weights: {'ExtraTreesMSE_BAG_L1': 0.421, 'NeuralNetTorch_BAG_L1': 0.263, 'RandomForestMSE_BAG_L1': 0.158, 'XGBoost_BAG_L1': 0.105, 'NeuralNetFastAI_BAG_L1': 0.053}
(_dystack pid=3067) 	0.33s	 = Training   runtime
(_dystack pid=3067) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: LightGBMXT_BAG_L2_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
(_dystack pid=3067) 	0.81s	 = Training   runtime
(_dystack pid=3067) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: LightGBM_BAG_L2_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
(_dystack pid=3067) 	0.55s	 = Training   runtime
(_dystack pid=3067) Fitting model: RandomForestMSE_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=3067) 	15.53s	 = Training   runtime
(_dystack pid=3067) 	0.3s	 = Validation runtime
(_dystack pid=3067) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: CatBoost_BAG_L2_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0
(_dystack pid=3067) 	4.08s	 = Training   runtime
(_dystack pid=3067) Fitting model: ExtraTreesMSE_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=3067) 	5.26s	 = Training   runtime
(_dystack pid=3067) 	0.29s	 = Validation runtime
(_dystack pid=3067) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=3067) Fitting model: NeuralNetFastAI_BAG_L2_FULL ...
(_dystack pid=3067) 	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/9.4 GB
(_dystack pid=3067) 	Stopping at the best epoch learned earlier - 10.
(_dystack pid=3067) 	4.51s	 = Training   runtime
(_dystack pid=3067) Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
(_dystack pid=3067) 	Ensemble Weights: {'CatBoost_BAG_L2': 0.933, 'ExtraTreesMSE_BAG_L2': 0.067}
(_dystack pid=3067) 	0.35s	 = Training   runtime
(_dystack pid=3067) Updated best model to "WeightedEnsemble_L3_FULL" (Previously "WeightedEnsemble_L3"). AutoGluon will default to using "WeightedEnsemble_L3_FULL" for predict() and predict_proba().
(_dystack pid=3067) Refit complete, total runtime = 56.14s ... Best model: "WeightedEnsemble_L3_FULL"
(_dystack pid=3067) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20260315_045809/ds_sub_fit/sub_fit_ho")
(_dystack pid=3067) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                          model  score_holdout  score_val          eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      WeightedEnsemble_L3_FULL      -1.508989  -1.692639  mean_absolute_error        0.703845            NaN  62.533692                 0.002715                     NaN           0.351371            3       True         16
1          CatBoost_BAG_L2_FULL      -1.512346  -1.694696  mean_absolute_error        0.538410            NaN  56.923846                 0.010045                     NaN           4.077444            2       True         13
2      WeightedEnsemble_L2_FULL      -1.596880  -1.855162  mean_absolute_error        0.470475            NaN  33.351820                 0.004552                     NaN           0.334307            2       True          9
3     ExtraTreesMSE_BAG_L1_FULL      -1.651440  -1.917483  mean_absolute_error        0.184136       0.270010   2.265763                 0.184136                0.270010           2.265763            1       True          5
4     ExtraTreesMSE_BAG_L2_FULL      -1.654836  -1.851100  mean_absolute_error        0.691085            NaN  58.104877                 0.162719                0.288872           5.258475            2       True         14
5    NeuralNetTorch_BAG_L1_FULL      -1.665105  -2.113768  mean_absolute_error        0.025118            NaN  16.757783                 0.025118                     NaN          16.757783            1       True          8
6          CatBoost_BAG_L1_FULL      -1.674479  -2.183734  mean_absolute_error        0.014575            NaN  16.878439                 0.014575                     NaN          16.878439            1       True          4
7   RandomForestMSE_BAG_L2_FULL      -1.721529  -1.903267  mean_absolute_error        0.697001            NaN  68.381381                 0.168636                0.296962          15.534979            2       True         12
8        LightGBMXT_BAG_L2_FULL      -1.729693  -2.043206  mean_absolute_error        0.565207            NaN  53.653023                 0.036842                     NaN           0.806621            2       True         10
9          LightGBM_BAG_L2_FULL      -1.743356  -2.146337  mean_absolute_error        0.546500            NaN  53.395502                 0.018134                     NaN           0.549100            2       True         11
10          XGBoost_BAG_L1_FULL      -1.824235  -2.007707  mean_absolute_error        0.018110            NaN   0.230447                 0.018110                     NaN           0.230447            1       True          7
11  RandomForestMSE_BAG_L1_FULL      -1.874704  -2.025510  mean_absolute_error        0.208489       0.332598   6.266814                 0.208489                0.332598           6.266814            1       True          3
12         LightGBM_BAG_L1_FULL      -1.985148  -2.260944  mean_absolute_error        0.014325            NaN   0.354376                 0.014325                     NaN           0.354376            1       True          2
13  NeuralNetFastAI_BAG_L2_FULL      -2.026353  -2.239276  mean_absolute_error        0.561307            NaN  57.357183                 0.032941                     NaN           4.510781            2       True         15
14       LightGBMXT_BAG_L1_FULL      -2.053568  -2.422665  mean_absolute_error        0.033542            NaN   2.596074                 0.033542                     NaN           2.596074            1       True          1
15  NeuralNetFastAI_BAG_L1_FULL      -2.736165  -2.172403  mean_absolute_error        0.030071            NaN   7.496706                 0.030071                     NaN           7.496706            1       True          6
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	989s	 = DyStack   runtime |	2611s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 2611s
AutoGluon will save models to "/content/AutogluonModels/ag-20260315_045809"
Train Data Rows:    5865
Train Data Columns: 15
Label Column:       days_to_report
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9633.42 MB
	Train Data (Original)  Memory Usage: 3.29 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['discode']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['cases_same_day', 'district_cases_day', 'province_case_count', 'district_case_count', 'report_weekday', ...]
		('int', [])    : 3 | ['agey', 'hospital_load', 'is_weekend_sick']
		('object', []) : 5 | ['Sex', 'province', 'district', 'occupat', 'treatmentloc']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 5 | ['Sex', 'province', 'district', 'occupat', 'treatmentloc']
		('float', [])     : 6 | ['cases_same_day', 'district_cases_day', 'province_case_count', 'district_case_count', 'report_weekday', ...]
		('int', [])       : 2 | ['agey', 'hospital_load']
		('int', ['bool']) : 1 | ['is_weekend_sick']
	0.2s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 0.39 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.3s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1740.14s of the 2610.83s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.21%)
	-2.3453	 = Validation score   (-mean_absolute_error)
	35.18s	 = Training   runtime
	1.47s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1699.36s of the 2570.06s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.20%)
	-2.2461	 = Validation score   (-mean_absolute_error)
	30.84s	 = Training   runtime
	0.16s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 1662.30s of the 2533.00s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.0/9.7 GB
	-1.9718	 = Validation score   (-mean_absolute_error)
	4.39s	 = Training   runtime
	0.42s	 = Validation runtime

In [ ]:
# model Leaderboard

predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetTorch_BAG_L2_FULL,-1.882306,NaN,mean_absolute_error,0.833651,NaN,183.471585,0.046261,NaN,30.136286,2,True,47
1,WeightedEnsemble_L3_FULL,-1.887567,NaN,mean_absolute_error,1.014780,NaN,196.647998,0.004291,NaN,0.392760,3,True,50
2,WeightedEnsemble_L2_FULL,-1.902673,NaN,mean_absolute_error,0.327903,NaN,111.782835,0.003682,NaN,0.335522,2,True,39
3,CatBoost_BAG_L2_FULL,-1.903830,NaN,mean_absolute_error,0.798646,NaN,160.594937,0.011256,NaN,7.259638,2,True,43
4,XGBoost_BAG_L1_FULL,-1.914598,NaN,mean_absolute_error,0.021953,NaN,0.322159,0.021953,NaN,0.322159,1,True,32
5,RandomForestMSE_BAG_L1_FULL,-1.923632,NaN,mean_absolute_error,0.191517,0.417942,4.386607,0.191517,0.417942,4.386607,1,True,28
6,RandomForestMSE_BAG_L1,-1.923632,-1.971788,mean_absolute_error,0.275878,0.417942,4.386607,0.275878,0.417942,4.386607,1,True,3
7,XGBoost_BAG_L2_FULL,-1.958460,NaN,mean_absolute_error,0.806741,NaN,153.652994,0.019351,NaN,0.317695,2,True,46
8,ExtraTreesMSE_BAG_L1_FULL,-1.964682,NaN,mean_absolute_error,0.183116,0.520118,3.447837,0.183116,0.520118,3.447837,1,True,30
9,ExtraTreesMSE_BAG_L1,-1.964682,-1.876189,mean_absolute_error,0.200977,0.520118,3.447837,0.200977,0.520118,3.447837,1,True,5
10,ExtraTreesMSE_BAG_L2_FULL,-1.968516,NaN,mean_absolute_error,0.961841,NaN,158.910185,0.174451,0.615986,5.574886,2,True,44
11,NeuralNetTorch_BAG_L1_FULL,-1.969181,NaN,mean_absolute_error,0.031815,NaN,54.869571,0.031815,NaN,54.869571,1,True,33
12,LightGBMLarge_BAG_L1_FULL,-1.977771,NaN,mean_absolute_error,0.047420,NaN,1.580611,0.047420,NaN,1.580611,1,True,34
13,CatBoost_r177_BAG_L2_FULL,-2.003042,NaN,mean_absolute_error,0.796129,NaN,155.855355,0.008739,NaN,2.520056,2,True,49
14,RandomForestMSE_BAG_L2_FULL,-2.043922,NaN,mean_absolute_error,0.995504,NaN,175.303610,0.208114,0.522685,21.968311,2,True,42
15,LightGBMXT_BAG_L2_FULL,-2.088595,NaN,mean_absolute_error,0.884602,NaN,154.616597,0.097212,NaN,1.281298,2,True,40
16,LightGBM_BAG_L1_FULL,-2.093381,NaN,mean_absolute_error,0.023079,NaN,0.436527,0.023079,NaN,0.436527,1,True,27
17,LightGBM_r131_BAG_L1_FULL,-2.105504,NaN,mean_absolute_error,0.107174,NaN,0.993119,0.107174,NaN,0.993119,1,True,37
18,LightGBMLarge_BAG_L2_FULL,-2.126278,NaN,mean_absolute_error,0.944233,NaN,156.339258,0.156843,NaN,3.003959,2,True,48
19,NeuralNetTorch_r79_BAG_L1_FULL,-2.129104,NaN,mean_absolute_error,0.039917,NaN,51.227135,0.039917,NaN,51.227135,1,True,36
20,LightGBM_BAG_L2_FULL,-2.322203,NaN,mean_absolute_error,0.845981,NaN,154.397281,0.058591,NaN,1.061982,2,True,41
21,NeuralNetFastAI_BAG_L1_FULL,-2.352468,NaN,mean_absolute_error,0.047699,NaN,9.649154,0.047699,NaN,9.649154,1,True,31
22,CatBoost_r177_BAG_L1_FULL,-2.381025,NaN,mean_absolute_error,0.010664,NaN,7.669793,0.010664,NaN,7.669793,1,True,35
23,LightGBMXT_BAG_L1_FULL,-2.450047,NaN,mean_absolute_error,0.105525,NaN,4.877448,0.105525,NaN,4.877448,1,True,26
24,CatBoost_BAG_L1_FULL,-2.465391,NaN,mean_absolute_error,0.019960,NaN,16.511362,0.019960,NaN,16.511362,1,True,29
25,NeuralNetFastAI_r191_BAG_L1_FULL,-3.568671,NaN,mean_absolute_error,0.063076,NaN,2.241424,0.063076,NaN,2.241424,1,True,38
26,NeuralNetFastAI_BAG_L2_FULL,-3.810226,NaN,mean_absolute_error,0.842417,NaN,154.912792,0.055027,NaN,1.577493,2,True,45
27,WeightedEnsemble_L3,NaN,-1.625839,mean_absolute_error,NaN,6.616392,2210.023268,NaN,0.002588,0.392760,3,False,25
28,WeightedEnsemble_L2,NaN,-1.663184,mean_absolute_error,NaN,1.506530,1153.091118,NaN,0.001875,0.335522,2,False,14
29,CatBoost_BAG_L2,NaN,-1.667670,mean_absolute_error,NaN,5.043869,1781.282224,NaN,0.112950,97.586960,2,False,18
30,CatBoost_r177_BAG_L2,NaN,-1.680546,mean_absolute_error,NaN,5.077774,1717.960134,NaN,0.146855,34.264870,2,False,24
31,NeuralNetTorch_BAG_L2,NaN,-1.715862,mean_absolute_error,NaN,5.451895,2013.396460,NaN,0.520977,329.701196,2,False,22
32,NeuralNetTorch_BAG_L1,NaN,-1.753397,mean_absolute_error,NaN,0.288820,615.822865,NaN,0.288820,615.822865,1,False,8
33,NeuralNetTorch_r79_BAG_L1,NaN,-1.798802,mean_absolute_error,NaN,0.332859,465.647134,NaN,0.332859,465.647134,1,False,11
34,ExtraTreesMSE_BAG_L2,NaN,-1.803229,mean_absolute_error,NaN,5.546905,1689.270150,NaN,0.615986,5.574886,2,False,19
35,XGBoost_BAG_L2,NaN,-1.854828,mean_absolute_error,NaN,5.499133,1724.954586,NaN,0.568214,41.259322,2,False,21
36,LightGBMLarge_BAG_L2,NaN,-1.861764,mean_absolute_error,NaN,5.833023,1748.077482,NaN,0.902104,64.382218,2,False,23
37,RandomForestMSE_BAG_L2,NaN,-1.875345,mean_absolute_error,NaN,5.453604,1705.663574,NaN,0.522685,21.968311,2,False,17
38,LightGBMXT_BAG_L2,NaN,-1.963973,mean_absolute_error,NaN,6.074269,1726.406188,NaN,1.143350,42.710924,2,False,15
39,LightGBM_BAG_L2,NaN,-1.999449,mean_absolute_error,NaN,5.327651,1725.439817,NaN,0.396732,41.744553,2,False,16
40,XGBoost_BAG_L1,NaN,-2.002699,mean_absolute_error,NaN,0.169173,33.305464,NaN,0.169173,33.305464,1,False,7
41,LightGBMLarge_BAG_L1,NaN,-2.009532,mean_absolute_error,NaN,0.193685,34.532295,NaN,0.193685,34.532295,1,False,9
42,CatBoost_r177_BAG_L1,NaN,-2.053700,mean_absolute_error,NaN,0.118173,100.845218,NaN,0.118173,100.845218,1,False,10
43,NeuralNetFastAI_BAG_L1,NaN,-2.081621,mean_absolute_error,NaN,0.425343,111.153057,NaN,0.425343,111.153057,1,False,6
44,LightGBM_r131_BAG_L1,NaN,-2.129954,mean_absolute_error,NaN,1.487489,37.995759,NaN,1.487489,37.995759,1,False,12
45,CatBoost_BAG_L1,NaN,-2.139066,mean_absolute_error,NaN,0.167542,176.300737,NaN,0.167542,176.300737,1,False,4
46,LightGBM_BAG_L1,NaN,-2.246092,mean_absolute_error,NaN,0.157904,30.835469,NaN,0.157904,30.835469,1,False,2
47,NeuralNetFastAI_BAG_L2,NaN,-2.277168,mean_absolute_error,NaN,5.477336,1789.269875,NaN,0.546417,105.574611,2,False,20
48,LightGBMXT_BAG_L1,NaN,-2.345337,mean_absolute_error,NaN,1.466918,35.180335,NaN,1.466918,35.180335,1,False,1
49,NeuralNetFastAI_r191_BAG_L1,NaN,-3.623970,mean_absolute_error,NaN,0.651872,69.422821,NaN,0.651872,69.422821,1,False,13

In [ ]:
# test Prediction

pred = predictor.predict(test_data)

In [ ]:
# check Feature Importance

predictor.feature_importance(test_data)

These features in provided data are not utilized by the predictor and will be ignored: ['discode']
Computing feature importance via permutation shuffling for 14 features using 1467 rows with 5 shuffle sets...
	75.23s	= Expected runtime (15.05s per shuffle set)
	35.09s	= Actual runtime (Completed 5 of 5 shuffle sets)

                     importance    stddev       p_value  n  p99_high   p99_low
report_month           1.526370  0.026871  1.152088e-08  5  1.581698  1.471043
Sex                    0.988949  0.065114  2.242233e-06  5  1.123020  0.854879
district               0.813953  0.094947  2.182087e-05  5  1.009451  0.618456
cases_same_day         0.722902  0.048038  2.326261e-06  5  0.821813  0.623991
province               0.584762  0.042420  3.300007e-06  5  0.672105  0.497418
report_weekday         0.444323  0.104136  3.370088e-04  5  0.658741  0.229904
treatmentloc           0.227016  0.048181  2.295177e-04  5  0.326222  0.127811
district_case_count    0.139649  0.028220  1.896535e-04  5  0.197754  0.081544
hospital_load          0.129554  0.022701  1.086449e-04  5  0.176296  0.082812
province_case_count    0.128841  0.019088  5.615254e-05  5  0.168142  0.089539
district_cases_day     0.096588  0.019891  2.041636e-04  5  0.137545  0.055631
occupat                0.045694  0.027144  9.851615e-03  5  0.101585 -0.010196
agey                   0.033504  0.027440  2.621620e-02  5  0.090004 -0.022996
is_weekend_sick       -0.002105  0.044518  5.395590e-01  5  0.089559 -0.093769

In [26]:
# Save training folder from Colab to Google Drive

from google.colab import drive
import os

# 1) Mount Google Drive
drive.mount('/content/drive')

# 2) กำหนด path ของ folder ที่ต้องการ save
source_folder = "/content/AutogluonModels"   # เปลี่ยนเป็น folder ที่คุณต้องการ
zip_name = "trained_model.zip"

# 3) zip folder
!zip -r $zip_name $source_folder

# 4) copy zip file ไป Google Drive
drive_path = "/content/drive/MyDrive/"
!cp $zip_name $drive_path

# 5) แสดงผลลัพธ์
print("Saved to Google Drive:", drive_path + zip_name)

Mounted at /content/drive
  adding: content/AutogluonModels/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/learner.pkl (deflated 67%)
  adding: content/AutogluonModels/ag-20260315_045809/version.txt (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/predictor.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F3/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F2/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F4/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F5/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F1/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F7/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/utils/model_template.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/utils/oof.pkl (deflated 65%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F6/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetFastAI_BAG_L1/S1F8/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1_FULL/S1F1/xgb.ubj (deflated 74%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1_FULL/S1F1/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1_FULL/model.pkl (deflated 52%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1_FULL/utils/model_template.pkl (deflated 45%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L1_FULL/S1F1/model.pkl (deflated 84%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L1_FULL/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L2/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L2/S1F1/model.pkl (deflated 82%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L2/model.pkl (deflated 52%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L2/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L2/utils/model_template.pkl (deflated 45%)
  adding: content/AutogluonModels/ag-20260315_045809/models/RandomForestMSE_BAG_L2/utils/oof.pkl (deflated 66%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1_FULL/S1F1/model.pkl (deflated 66%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1_FULL/model.pkl (deflated 52%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1_FULL/utils/model_template.pkl (deflated 43%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F3/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F2/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F4/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F5/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F1/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F7/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/utils/model_template.pkl (deflated 42%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/utils/oof.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F6/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_r177_BAG_L1/S1F8/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L1_FULL/S1F1/model.pkl (deflated 66%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L1_FULL/model.pkl (deflated 52%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L1_FULL/utils/model_template.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_BAG_L2_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_BAG_L2_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_BAG_L2_FULL/S1F1/model.pkl (deflated 68%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_BAG_L2_FULL/model.pkl (deflated 59%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_BAG_L2_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/CatBoost_BAG_L2_FULL/utils/model_template.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L2_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L2_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L2_FULL/S1F1/model.pkl (deflated 64%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L2_FULL/model.pkl (deflated 59%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L2_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L2_FULL/utils/model_template.pkl (deflated 45%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F3/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F2/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F4/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F5/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F1/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F7/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/model.pkl (deflated 52%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/utils/model_template.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/utils/oof.pkl (deflated 60%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F6/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBM_BAG_L2/S1F8/model.pkl (deflated 54%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F3/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F2/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F4/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F5/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F1/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F7/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/utils/oof.pkl (deflated 61%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F6/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMLarge_BAG_L1/S1F8/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L2_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L2_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L2_FULL/S1F1/model.pkl (deflated 64%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L2_FULL/model.pkl (deflated 59%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L2_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/LightGBMXT_BAG_L2_FULL/utils/model_template.pkl (deflated 45%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F3/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F2/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F4/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F5/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F1/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F7/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/utils/oof.pkl (deflated 59%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F6/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L1/S1F8/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ExtraTreesMSE_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ExtraTreesMSE_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ExtraTreesMSE_BAG_L1/S1F1/model.pkl (deflated 80%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ExtraTreesMSE_BAG_L1/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ExtraTreesMSE_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ExtraTreesMSE_BAG_L1/utils/model_template.pkl (deflated 45%)
  adding: content/AutogluonModels/ag-20260315_045809/models/ExtraTreesMSE_BAG_L1/utils/oof.pkl (deflated 66%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F3/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F2/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F4/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F5/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F1/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F7/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/utils/model_template.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/utils/oof.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F6/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/NeuralNetTorch_BAG_L1/S1F8/model.pkl (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L2_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L2_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L2_FULL/S1F1/xgb.ubj (deflated 73%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L2_FULL/S1F1/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_045809/models/XGBoost_BAG_L2_FULL/model.pkl (deflated 59%)